# Generated by Django 4.0.5 on 2022-07-13 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Father_Name', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=25)),
                ('Mobile', models.CharField(max_length=15)),
                ('CNIC', models.CharField(max_length=15)),
                ('Resident_Address', models.CharField(max_length=255)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Debtor Details',
            },
        ),
        migrations.CreateModel(
            name='Employee_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_of_Join', models.DateField()),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Mobile', models.CharField(max_length=25)),
                ('CNIC', models.CharField(max_length=255)),
                ('Resident_Address', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('Salary', models.IntegerField()),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Details',
            },
        ),
        migrations.CreateModel(
            name='Supplier_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=13)),
                ('IBAN', models.CharField(max_length=20)),
                ('Bank_Name', models.CharField(max_length=20)),
                ('Company_Name', models.CharField(max_length=55)),
                ('Resident_Address', models.CharField(max_length=30)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Supplier Details',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Petrol_Price', models.FloatField()),
                ('Diesel_Price', models.FloatField()),
                ('Petrol_ReadingA', models.FloatField()),
                ('Petrol_ReadingB', models.FloatField()),
                ('Petrol_ReadingC', models.FloatField()),
                ('Petrol_ReadingD', models.FloatField()),
                ('Total_Petrol_Sold', models.FloatField()),
                ('Total_Petrol_Rs', models.FloatField()),
                ('Diesel_ReadingA', models.FloatField()),
                ('Diesel_ReadingB', models.FloatField()),
                ('Total_Diesel_Sold', models.FloatField()),
                ('Total_Diesel_Rs', models.FloatField()),
                ('Today_Sale_Man', models.CharField(max_length=25)),
                ('Tonight_Sale_Man', models.CharField(max_length=25)),
                ('Today_Total_Expenses', models.FloatField()),
                ('Today_Total_Credit', models.FloatField()),
                ('Today_Total_Debit', models.FloatField()),
                ('Today_Rs', models.FloatField()),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Summaries',
            },
        ),
        migrations.CreateModel(
            name='Login_Statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.CharField(max_length=25)),
                ('Date', models.DateField()),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supply_Date', models.DateField()),
                ('Petrol_Supplied_Ltrs', models.FloatField()),
                ('Petrol_Supply_Rs', models.FloatField()),
                ('Diesel_Supplied_Ltrs', models.FloatField()),
                ('Diesel_Supply_Rs', models.FloatField()),
                ('Supplier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.supplier_detail')),
            ],
            options={
                'verbose_name_plural': 'Fuel Supplies',
            },
        ),
        migrations.CreateModel(
            name='Fuel_Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Petrol_In_Stock', models.FloatField()),
                ('Total_Diesel_In_Stock', models.FloatField()),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.summary')),
            ],
            options={
                'verbose_name_plural': 'Fuel Stock',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_Name', models.CharField(max_length=25)),
                ('Expense_Price', models.IntegerField()),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.summary')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary_Date', models.DateField()),
                ('Total_Paid_Rs', models.IntegerField()),
                ('Total_Remained_Rs', models.IntegerField()),
                ('Salary_Status', models.CharField(max_length=20)),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.employee_detail')),
            ],
            options={
                'verbose_name_plural': 'Employees Salaries',
            },
        ),
        migrations.CreateModel(
            name='Debtor_Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Debt_Date', models.DateField()),
                ('Today_Credit', models.FloatField()),
                ('Today_Debt', models.FloatField()),
                ('Current_Total_Debt', models.FloatField()),
                ('Debtor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.debtor_detail')),
            ],
            options={
                'verbose_name_plural': 'Debtor Dues',
            },
        ),
        migrations.CreateModel(
            name='Cash_Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Cashed_In', models.FloatField()),
                ('Cashed_In_Reason', models.CharField(max_length=255)),
                ('Cashed_Out', models.FloatField()),
                ('Cashed_Out_Reason', models.CharField(max_length=255)),
                ('Total_Month_Rs', models.FloatField()),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.summary')),
            ],
            options={
                'verbose_name_plural': 'Cash Transactions',
            },
        ),
        migrations.CreateModel(
            name='Account_Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Owner', models.CharField(max_length=255)),
                ('Second_Owner', models.CharField(default=None, max_length=255)),
                ('Pump_Name', models.CharField(max_length=255)),
                ('Pump_Address', models.CharField(max_length=255)),
                ('First_Owner_Mobile', models.CharField(max_length=255)),
                ('Secon_Owner_Mobile', models.CharField(default=None, max_length=255)),
                ('Owner_Email', models.CharField(max_length=255)),
                ('Pump_Reg_No', models.CharField(max_length=255)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Account Details',
            },
        ),
    ]
