# Generated by Django 4.0.5 on 2022-08-12 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_Dependences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_of_Installation', models.DateField(auto_now=True)),
                ('Hardware_Name', models.CharField(max_length=100)),
                ('Hardware_Id', models.CharField(max_length=255)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
